### ISSUE TITLE
Fix Console ROT13 cipher

### ISSUE THREAD

**Issue by aphawkins** [aphawkins/useful#14]
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
  Source=Useful.UI
  StackTrace:
   at Useful.UI.Controllers.SettingsController..ctor(ICipherSettings cipherSettings, ICipherSettingsView cipherSettingsView) in C:\code\github\aphawkins\useful\src\Useful.UI\Controllers\SettingsController.cs:line 25
   at Useful.UI.Controllers.CipherController.SelectCipher(ICipher cipher, ICipherSettingsView settingsView) in C:\code\github\aphawkins\useful\src\Useful.UI\Controllers\CipherController.cs:line 72
   at UsefulConsole.UI.Views.ConsoleView.DisplayCipherSelect(IList`1 ciphers) in C:\code\github\aphawkins\useful\src\UsefulConsole\UI\Views\ConsoleView.cs:line 61
   at UsefulConsole.UI.Views.ConsoleView.Initialize() in C:\code\github\aphawkins\useful\src\UsefulConsole\UI\Views\ConsoleView.cs:line 73
   at Useful.UI.Controllers.CipherController.LoadView() in C:\code\github\aphawkins\useful\src\Useful.UI\Controllers\CipherController.cs:line 60
   at UsefulConsole.UI.Console.Program.Main() in C:\code\github\aphawkins\useful\src\UsefulConsole\UI\Console\Program.cs:line 20

**Comment by aphawkins** [comment]
Fixed.
